name = "bananahub-api"
main = "src/index.js"
compatibility_date = "2025-03-01"

[[kv_namespaces]]
binding = "INSTALLS"
id = "cc55f1747c7b448caa2e4e0c648a353c"
preview_id = "8538ba8010a64e86ab1671c017130e2f"
